<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-08-03 19:03:53
 */
return [
    'yii\bootstrap\BootstrapAsset' => [
        'sourcePath' => null,
        'css'=>[
            '//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css'
        ]
    ],
    'yii\bootstrap\BootstrapPluginAsset' => [
        'sourcePath' => null,
        'js' => [
            '//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js'
        ]
    ],
    'yii\web\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [
            '//cdn.bootcss.com/jquery/1.9.1/jquery.min.js '
        ]
    ],
];