<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual only' => 'Actual only',
    'All records' => 'All records',
    'Are you sure you want to restore defaults?' => 'Are you sure you want to restore defaults?',
    'Are you sure you want to restore this item?' => 'Are you sure you want to restore this item?',
    'Back' => 'Back',
    'Context \'{name}\' required.' => 'Context \'{name}\' required.',
    'Context object not found: {id}' => 'Context object not found: {id}',
    'Create' => 'Create',
    'Delete' => 'Delete',
    'Deleted' => 'Deleted',
    'Import' => 'Import',
    'Move bottom' => 'Move bottom',
    'Move down' => 'Move down',
    'Move top' => 'Move top',
    'Move up' => 'Move up',
    'Object not found: {id}' => 'Object not found: {id}',
    'Restore' => 'Restore',
    'Restore Defaults' => 'Restore Defaults',
    'Update' => 'Update',
    'View' => 'View',
];
