<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual only' => 'Apenas atual',
    'All records' => 'Todos registros',
    'Are you sure you want to restore defaults?' => 'Tem certeza de que deseja restaurar os padrões?',
    'Are you sure you want to restore this item?' => 'Tem certeza de que deseja restaurar este item?',
    'Back' => 'Voltar',
    'Context \'{name}\' required.' => 'Contexto \'{name}\' necessário.',
    'Context object not found: {id}' => 'Contexto objeto não encontrado: {id}',
    'Create' => 'Criar',
    'Delete' => 'Excluir',
    'Deleted' => 'Excluído',
    'Import' => 'Importar',
    'Move bottom' => 'Mover inferior',
    'Move down' => 'Mover para baixo',
    'Move top' => 'Mover topo',
    'Move up' => 'Mover para cima',
    'Object not found: {id}' => 'Objeto não encontrado: {id}',
    'Restore' => 'Restaurar',
    'Restore Defaults' => 'Restaurar padrões',
    'Update' => 'Atualizar',
    'View' => 'Visualizar',
];
