<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual only' => 'Только актуальные',
    'All records' => 'Все записи',
    'Are you sure you want to restore defaults?' => 'Вы уверены, что хотите восстановить значения по умолчанию?',
    'Are you sure you want to restore this item?' => 'Вы уверены, что хотите восстановить этот элемент?',
    'Back' => 'Назад',
    'Context \'{name}\' required.' => 'Контекст \'{name}\' должен быть задан.',
    'Context object not found: {id}' => 'Контекстный объект не найден: {id}',
    'Create' => 'Создать',
    'Delete' => 'Удалить',
    'Deleted' => 'Удалено',
    'Import' => 'Импорт',
    'Move bottom' => 'Переместить в конец',
    'Move down' => 'Переместить вниз',
    'Move top' => 'Переместить в начало',
    'Move up' => 'Переместить вверх',
    'Object not found: {id}' => 'Объект не найден: {id}',
    'Restore' => 'Восстановить',
    'Restore Defaults' => 'По умолчанию',
    'Update' => 'Редактировать',
    'View' => 'Просмотр',
];
