<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual only' => 'Тільки актуальні',
    'All records' => 'Усі записи',
    'Are you sure you want to restore defaults?' => 'Ви впевнені, що хочете відновити стандартні значення?',
    'Are you sure you want to restore this item?' => 'Ви впевнені, що хочете відновити цей елемент?',
    'Back' => 'Назад',
    'Context \'{name}\' required.' => 'Контекст \'{name}\' має бути заданий.',
    'Context object not found: {id}' => 'Котекстний об\'єкт не знайдено: {id}',
    'Create' => 'Створити',
    'Delete' => 'Видалити',
    'Deleted' => 'Видалено',
    'Import' => 'Імпорт',
    'Move bottom' => 'Перемістити в кінець',
    'Move down' => 'Перемістити вниз',
    'Move top' => 'Перемістити на початок',
    'Move up' => 'Перемістити вгору',
    'Object not found: {id}' => 'Об\'єкт не знайдено: {id}',
    'Restore' => 'Відновити',
    'Restore Defaults' => 'Відновити стандарт',
    'Update' => 'Оновити',
    'View' => 'Переглянути',
];
