<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actual only' => 'Actual unicamente',
    'All records' => 'Todos los Registro',
    'Are you sure you want to restore defaults?' => '¿Esta seguro que quiere restaurar por defecto?',
    'Are you sure you want to restore this item?' => '¿Esta seguro que quiere restaurar este artículo',
    'Back' => 'Volver',
    'Context \'{name}\' required.' => 'Contexto \'{name}\' requerido.',
    'Context object not found: {id}' => 'Objeto de contexto no encontrado: {id}',
    'Create' => 'Сrear',
    'Delete' => 'Borrar',
    'Deleted' => 'Borrado',
    'Import' => 'Importar',
    'Move bottom' => 'Mover al fondo',
    'Move down' => 'Mover abajo',
    'Move top' => 'Mover al tope',
    'Move up' => 'Mover arriva',
    'Object not found: {id}' => 'Objeto no encontrado: {id}',
    'Restore' => 'Restaurar',
    'Restore Defaults' => 'Restaurar valores por defecto',
    'Update' => 'Actualizar',
    'View' => 'Ver',
];
